name: Deploy BCLUG Website

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Git
      run: |
        git config user.name "GitHub Actions"
        git config user.email "noreply@github.com"

    - name: Deploy to web server
      env:
        PRIVATE_KEY: ${{ secrets.WEBSITE_PRIVATE_KEY }}
        HOST: bclug.org
        USERNAME: bclug
        REMOTE_PATH: /home/bclug/public_html/
      run: |
        echo "$PRIVATE_KEY" > private_key.pem
        chmod 600 private_key.pem

        rsync -avz -e "ssh -i private_key.pem -o StrictHostKeyChecking=no" --delete --exclude '.git' --exclude '.github' website/ $USERNAME@$HOST:$REMOTE_PATH

        rm -f private_key.pem

